'use client';
import Link from 'next/link';
import { useState } from 'react';
import type { TopologyNode, PhysicalPoint } from '@/modules/topology/domain/entities';
import type { VisualStageChild } from './topology-visual-stage';
export function TopologyExplorer({ node, items, boundary }: { node: TopologyNode; items: readonly VisualStageChild[]; boundary?: readonly PhysicalPoint[] | undefined }) {
  const [selected,setSelected] = useState<string | null>(null); const [zoom,setZoom] = useState(1);
  const item = items.find(i => i.node.id === selected); const polygons = items.flatMap(i => 'polygon' in i.node && i.node.polygon ? [...i.node.polygon] : []);
  const all = [...(boundary ?? []), ...polygons]; const hasGeometry = polygons.length > 0 && node.kind !== 'STRUCTURE';
  const minX = Math.min(...all.map(p => p.x),0), minY=Math.min(...all.map(p => p.y),0); const width=Math.max(...all.map(p=>p.x),1200)-minX, height=Math.max(...all.map(p=>p.y),1200)-minY; const pad=Math.max(width,height)*.1;
  const points = (p:readonly PhysicalPoint[]) => p.map(v=>`${v.x},${v.y}`).join(' ');
  return <section className="mk-explorer"><div className="mk-explorer-main"><header><strong>{node.kind === 'STRUCTURE' ? 'LEVELS' : node.name.toUpperCase()}</strong><small>{hasGeometry ? 'PHYSICAL GEOMETRY · mm' : 'TOPOLOGICAL VIEW · NOT TO SCALE'}</small></header>
    <div className="mk-map-canvas"><div className="mk-map-zoom" style={{transform:`scale(${zoom})`}}>
      {hasGeometry ? <svg viewBox={`${minX-pad} ${minY-pad} ${width+pad*2} ${height+pad*2}`} aria-label="Physical layout">{boundary && <polygon points={points(boundary)} className="mk-map-boundary" />}{items.map(entry=> { const p='polygon' in entry.node ? entry.node.polygon : undefined; if (!p?.length) return null; return <g key={entry.node.id} tabIndex={0} role="button" aria-label={`Select ${entry.node.name}`} onClick={()=>setSelected(entry.node.id)} onDoubleClick={()=>window.location.assign(entry.href)} onKeyDown={e=>{if(e.key==='Enter')setSelected(entry.node.id);}}><polygon points={points(p)} className={selected===entry.node.id?'is-selected':''}/><text x={p.reduce((s,v)=>s+v.x,0)/p.length} y={p.reduce((s,v)=>s+v.y,0)/p.length} style={{fontSize:Math.max(width,height)*.024}} textAnchor="middle">{entry.node.name}</text></g>;})}</svg> : <div className={node.kind==='STRUCTURE'?'mk-level-stack':'mk-node-map'}>{items.map(entry=><button key={entry.node.id} className={`mk-map-node ${selected===entry.node.id?'is-selected':''}`} onClick={()=>setSelected(entry.node.id)} onDoubleClick={()=>window.location.assign(entry.href)}><span className="mk-building-glyph" aria-hidden="true">▥</span><strong>{entry.node.name}</strong><small>{entry.node.kind === 'ROOM_SUBSTRUCTURE'?'ROOM':entry.node.kind}</small></button>)}</div>}
    </div></div><footer><span>{items.length} objects · click to inspect / double-click to open</span><button onClick={()=>setZoom(z=>Math.max(.5,z-.1))} aria-label="Zoom out">−</button><b>{Math.round(zoom*100)}%</b><button onClick={()=>setZoom(z=>Math.min(2,z+.1))} aria-label="Zoom in">+</button><button onClick={()=>setZoom(1)}>FIT VIEW</button></footer></div>
    <aside className="mk-inline-inspector"><small>INSPECTOR</small><h2>{item?.node.name ?? node.name}</h2><dl><dt>Type</dt><dd>{item?.node.kind.replaceAll('_',' ') ?? node.kind}</dd><dt>Lifecycle</dt><dd>{item?.node.lifecycle ?? node.lifecycle}</dd><dt>Context</dt><dd>{node.name}</dd></dl>{item ? <Link className="mk-primary" href={item.href}>OPEN {item.node.kind === 'ROOM_SUBSTRUCTURE'?'ROOM':item.node.kind} →</Link> : <p>Select an object to inspect its properties.</p>}</aside></section>;
}
